version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: transbantu-hr-db
    environment:
      POSTGRES_DB: transbantu_hr
      POSTGRES_USER: hr_admin
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - transbantu-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: transbantu-hr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - transbantu-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transbantu-hr-backend
    environment:
      DATABASE_URL: postgresql://hr_admin:secure_password@postgres:5432/transbantu_hr
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - transbantu-network
    command: npm run dev

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transbantu-hr-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - transbantu-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  transbantu-network:
    driver: bridge